#cloud-config
hostname: kaspersky-1
users:
  - name: marksista
    groups: wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJzaoAQLZNVv1MwQigPOPC563GT62xZXOdCvoqzHz1GV

packages:
  - git
  - curl
  - dnf-plugins-core
  - python3
  - python3-pip

runcmd:
  - firewall-cmd --permanent --add-port=8080/tcp && firewall-cmd --permanent --add-service=ssh
  - firewall-cmd --reload
  - dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - dnf install -y docker-ce docker-ce-cli containerd.io
  - systemctl enable --now docker
  - usermod -aG docker marksista
  - docker run hello-world
